### ISSUE TITLE
Objects not loaded after repeated put

### ISSUE THREAD

**Issue by pejrak** [chad3814/node-hashtable#11]
Hi, I ran into the below problem with versions 0.4+, and 

_node -v: v0.10.30_

The error:

> node hashtable_test3.js
/home/nol/webapps/tester/hashtable_test3.js:13
  item.members.push(i)
               ^
TypeError: Cannot call method 'push' of undefined
    at Object.<anonymous> (/home/nol/webapps/tester/hashtable_test3.js:13:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

```javascript
// File contents (test_hashtable.js)
var ht = require("hashtable")
var hash = new ht()

for (var i=0; i<10000; i++) {
  // Create id under which several members will be added
  var id = Math.round(i / (Math.random() * 100))
  var item = hash.get(id) || {
        id: id,
        members: []
      }

  item.members.push(i)
  hash.put(id, item)
}

console.log("Hash size:", hash.size())

// Finishes and returns size with hashtable@0.1.4
// Breaks with hashtable@0.4+
```

**Comment by chad3814** [comment]
I'm sorry everyone, for some reason I never got emails about these new issues and pull requests, does this still happen in 0.5.2?

**Comment by chad3814** [comment]
looks like this should still be a problem with 0.5.2, I'm so sorry. I've mostly focused on es6-native-set and es6-native-map (I used this node-hashtable code as the basis for them) since that's what we use at work, I'll merge this change and push a new version.
