### ISSUE TITLE
Non-string keys

### ISSUE THREAD

**Issue by BHare1985** [chad3814/node-hashtable#23]
Is this a possible feature?

Would like to use this like a ES6's Map and use numbers as keys (preferably with real 4byte integers and/or 8byte int64) but a standard 8byte double-precision floating-point format numbers would suffice

**Comment by chad3814** [comment]
that already works actually, any value except null and undefined are valid keys. I added that when I took this project over and wanted an es6 map interface; later I split the es6 map out into a separate module https://github.com/chad3814/es6-native-map.

**Comment by chad3814** [comment]
(I'll update the readme to reflect this)
