### ISSUE TITLE
fatal error: 'tr1/unordered_map' file not found

### ISSUE THREAD

**Issue by leyeye** [chad3814/node-hashtable#38]
Sorry! My English is not good,so I hope you can understand the issues 
Tell the author that this fails on your system:
npm ERR!     node-gyp configure build

**Comment by gerhardcit** [comment]
Same here.. anybody have suggestions for a replacement of this lib?
```
 node-gyp configure build

  CXX(target) Release/obj.target/native/src/hashtable.o
In file included from ../src/hashtable.cpp:1:
../src/hashtable.h:7:10: fatal error: 'tr1/unordered_map' file not found
#include <tr1/unordered_map>
```

**Comment by chad3814** [comment]
I would suggest the builtin Map: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
